const weatherIcons = {
    200: "assets/thunderstorm.svg",
    201: "assets/thunderstorm.svg",
    202: "assets/thunderstorm.svg",
    230: "assets/thunderstorm.svg",
    231: "assets/thunderstorm.svg",
    232: "assets/thunderstorm.svg",
    233: "assets/thunderstorm.svg",
    300: "assets/light-drizzle.svg",
    301: "assets/light-drizzle.svg",
    302: "assets/light-drizzle.svg",
    500: "assets/light-drizzle.svg",
    501: "assets/rain.svg",
    502: "assets/rain.svg",
    511: "assets/sleet.svg",
    520: "assets/rain.svg",
    521: "assets/rain.svg",
    522: "assets/rain.svg",
    600: "assets/snow.svg",
    601: "assets/snow.svg",
    602: "assets/snow.svg",
    610: "assets/snowfall.svg",
    611: "assets/sleet.svg",
    612: "assets/sleet.svg",
    621: "assets/snow.svg",
    622: "assets/snow.svg",
    623: "assets/snow.svg",
    700: "assets/partly-cloudy.svg",
    711: "assets/partly-cloudy.svg",
    721: "assets/partly-cloudy.svg",
    731: "assets/partly-cloudy.svg",
    741: "assets/partly-cloudy.svg",
    751: "assets/snow.svg",
    800: "assets/sunny.svg",
    801: "assets/sun-cloud.svg",
    802: "assets/sun-cloud.svg",
    803: "assets/sun-cloud.svg",
    804: "assets/sun-cloud.svg",
}

export default function getWeatherIcon(code) {
  return weatherIcons[code] || "/assets/default.svg";
}